name: build
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/yarn
            ~/.cache/ms-playwright
          key: build-${{ runner.os }}-yarn-v5-${{ hashFiles('yarn.lock') }}
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/bin/cargo-deny
            ~/.cargo/advisory-db/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git
            ./target/*/deps
            ./target/*/build
            ./target/*/.fingerprint
          key: build-${{ runner.os }}-rust-v9-${{ hashFiles('Cargo.lock', 'rust-toolchain') }}
      - run: ci/build.sh
      - name: Cleanup artifacts
        if: always()
        run: |
          if [[ "${RUNNER_OS:-}" == "Linux" ]]; then
              shopt -s globstar
              # The git-platinum repository contains paths that
              # contain a colon (:). These paths cannot be uploaded as
              # artifacts
              rm -rf test/e2e/**-state/**/*-checkouts/git-platinum
          fi
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-logs-${{ runner.os }}
          path: |
            test-results/**/*.zip
            test/e2e/*--state/**
