name: build
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/yarn
            ~/cache/cypress
            ~/.cache/ms-playwright
          key: build-${{ runner.os }}-yarn-v5-${{ hashFiles('yarn.lock') }}
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/bin/cargo-deny
            ~/.cargo/advisory-db/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git
            ./target/*/deps
            ./target/*/build
            ./target/*/.fingerprint
          key: build-${{ runner.os }}-rust-v9-${{ hashFiles('Cargo.lock', 'rust-toolchain') }}
      - run: ci/build.sh
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-logs-${{ runner.os }}
          path: |
            cypress/screenshots/**/*.png
            cypress/workspace/test-tmp/*/node-*/*.log
            cypress/workspace/test-tmp/*/combined-node.log
