name: dist
on:
  push:
    branches:
    - main
    - "**"
    - release-candidate/**

jobs:
  dist:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/yarn
          # Reuses cache from `build` workflow
          key: build-${{ runner.os }}-yarn-v5-${{ hashFiles('yarn.lock') }}
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git
            ./target/*/deps
            ./target/*/build
            ./target/*/.fingerprint
          key: ${{ github.job }}-${{ runner.os }}-rust-v9-${{ hashFiles('Cargo.lock', 'rust-toolchain') }}
      - run: ci/dist.sh
      - name: publish artifacts by commit
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: artifacts
          destination: radicle-upstream-build-artifacts/v1/by-commit/${{ github.sha }}
          credentials: ${{ secrets.GCP_SECRET_KEY }}
          parent: false
      - name: publish main artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: artifacts
          destination: radicle-upstream-build-artifacts/v1/main/
          credentials: ${{ secrets.GCP_SECRET_KEY }}
          parent: false
